### PR TITLE
Added support for differents shapes.

### PR DESCRIPTION
**Pull request by 942v**
Added shape source to manage custom colors and shapes. 

Nice control dude, this was the thing I was looking for. I hope you like my additions. 

You can check the demo, I've added an example of my changes.

### CODE REVIEW

**Comment by ogubariev** [comment]
Thanks for your improvements! It's really nice feature!

**Comment by 942v** [comment]
👍🏻 don't forget to update the pod version

**Comment by ogubariev** [comment]
I'm working on it now, thanks for your help!

**Comment by ogubariev** [comment]
I've finished with it! You can try new version now!)

**Comment by 942v** [comment]
👍🏻 keep the good work! BTW I made the shapes with paintcode.

**Pull request merged**
